function myBirthYearFunc(){
    console.log("Nací en " + 1980);
}
// Respuesta: El console.log indica "naci en 1980" //
function myBirthYearFunc(EntradaAñoNacimiento){
    console.log("Nací en " + EntradaAñoNacimiento);
}
// Respuesta: naci en 2006//

function add(num1, num2){
    console.log("¡Sumando números!");
    console.log("num1 is: " + num1);
    console.log("num2 is: " + num2);
    var sum = num1 + num2;
    console.log(sum);
}

// respuesta: el console.log indica: que la suma de los numeros 10+20 es 30 //
